name: "Repo Visualizer"
description: "A GitHub Action that creates an SVG diagram of your repo"
author: "GitHub OCTO"
inputs:
  output_file:
    description: "A path (relative to the root of your repo) to where you would like the diagram to live. For example: images/diagram.svg. Default: diagram.svg"
    required: false
  excluded_paths:
    description: "A list of paths to exclude from the diagram, separated by commas. For example: dist,node_modules"
    required: false
runs:
  using: "node12"
  main: "index.js"
branding:
  color: "purple"
  icon: "target"
