name: "Repo Visualizer"
description: "A GitHub Action that creates an SVG diagram of your repo"
author: "GitHub OCTO"
inputs:
  output_file:
    description: "A path (relative to the root of your repo) to where you would like the diagram to live. For example: images/diagram.svg. Default: diagram.svg"
    required: false
  excluded_paths:
    description: "A list of paths to exclude from the diagram, separated by commas. For example: dist,node_modules"
    required: false
  max_depth:
    description: "The maximum number of nested folders to show files within. Default: 9"
    required: false
  commit_message:
    description: "The commit message to use when updating the diagram. Default: Repo visualizer: updated diagram"
    required: false
  branch:
    description: "If you want to push the diagram to a different branch (branch will be created if it does not exist)"
    required: false
runs:
  using: "node12"
  main: "index.js"
branding:
  color: "purple"
  icon: "target"
